const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='figuritas_v2'; const colors=['#22d3ee','#3b82f6','#8b5cf6','#ec4899','#ef4444','#f97316','#eab308','#22c55e'];
let state={v:2,albums:[],activeId:null}, filter='all', range='all', editId=null, copyTarget=null, undoStack=[], coverData='';
const uid=()=>crypto.randomUUID?.()||Date.now()+Math.random().toString(36); const iso=()=>new Date().toISOString();
function album(){return state.albums.find(a=>a.id===state.activeId)||state.albums[0]}
function normalize(a){a.total=Math.max(1,Math.min(5000,+a.total||100));a.copies=a.copies||{};Object.keys(a.copies).forEach(k=>{let n=+k,q=Math.max(0,+a.copies[k]||0);if(n<1||n>a.total||!q)delete a.copies[k];else a.copies[k]=q});a.history=a.history||[];a.color=a.color||colors[0];a.updatedAt=a.updatedAt||iso();a.cover=a.cover||''}
function load(){try{let x=JSON.parse(localStorage.getItem(KEY));if(x?.v===2&&Array.isArray(x.albums))state=x}catch{}if(!state.albums.length){let a={id:uid(),name:'Mi Álbum',total:100,copies:{},history:[],color:colors[0],cover:'',updatedAt:iso()};state.albums=[a];state.activeId=a.id}state.albums.forEach(normalize);if(!album())state.activeId=state.albums[0].id;save()}
function save(){localStorage.setItem(KEY,JSON.stringify(state))} function toast(t){$('#toastText').textContent=t;bootstrap.Toast.getOrCreateInstance($('#toast'),{delay:1800}).show()}
function stats(a){let have=0,dups=0;for(let i=1;i<=a.total;i++){let q=a.copies[i]||0;if(q>0)have++;if(q>1)dups+=q-1}return{have,dups,missing:a.total-have,pct:Math.round(have/a.total*100)}}
function applyTheme(){document.documentElement.style.setProperty('--accent',album()?.color||colors[0])}
function action(desc,fn){let a=album();undoStack.push(JSON.stringify(a));if(undoStack.length>30)undoStack.shift();fn();a.updatedAt=iso();a.history.unshift({t:iso(),msg:desc});a.history=a.history.slice(0,40);save();render()}
function fmtDate(x){return new Date(x).toLocaleString('es-PE',{dateStyle:'short',timeStyle:'short'})}
function renderCards(){let box=$('#albumCards');box.innerHTML='';state.albums.forEach(a=>{let s=stats(a),el=document.createElement('article');el.className='album-card '+(a.id===state.activeId?'selected':'');el.innerHTML=`<div class="album-cover" ${a.cover?`style="background-image:url('${a.cover}')"`:''}>${a.cover?'':'<i class="bi bi-collection"></i>'}</div><div class="album-body"><div class="d-flex justify-content-between gap-2"><h3>${esc(a.name)}</h3><b>${s.pct}%</b></div><div class="progress my-2" style="height:7px"><div class="progress-bar" style="width:${s.pct}%"></div></div><small class="muted">${s.have}/${a.total} · Faltan ${s.missing} · ${s.dups} repetidas</small><small class="muted d-block mt-1">${fmtDate(a.updatedAt)}</small></div>`;el.onclick=()=>{state.activeId=a.id;save();render()};box.append(el)})}
function renderDash(){let a=album(),s=stats(a);$('#dashboard').innerHTML=`<div class="dash"><div class="d-flex justify-content-between flex-wrap gap-2 mb-3"><div><h2 class="h5 mb-1">${esc(a.name)}</h2><span class="muted">Última modificación: ${fmtDate(a.updatedAt)}</span></div><div class="d-flex gap-2"><button class="btn btn-ghost btn-sm" onclick="editAlbum()"><i class="bi bi-pencil"></i> Editar</button><button class="btn btn-outline-danger btn-sm" onclick="deleteAlbum()"><i class="bi bi-trash"></i></button></div></div><div class="stats"><div class="stat"><small>TOTAL</small><strong>${a.total}</strong></div><div class="stat"><small>TENGO</small><strong>${s.have}</strong></div><div class="stat"><small>ME FALTAN</small><strong>${s.missing}</strong></div><div class="stat"><small>REPETIDAS</small><strong>${s.dups}</strong></div><div class="stat"><small>COMPLETO</small><strong>${s.pct}%</strong></div></div><div class="progress mt-3" style="height:11px"><div class="progress-bar" style="width:${s.pct}%"></div></div><div class="d-flex gap-2 mt-3 flex-wrap"><button class="btn btn-accent" onclick="showView('numbers')"><i class="bi bi-grid-3x3-gap"></i> Ver números</button><button class="btn btn-ghost" onclick="showView('trade')"><i class="bi bi-arrow-left-right"></i> Intercambio</button><button class="btn btn-ghost" onclick="clearDups()"><i class="bi bi-eraser"></i> Limpiar repetidas</button><button class="btn btn-outline-danger" onclick="resetAlbum()"><i class="bi bi-arrow-repeat"></i> Reset</button></div><hr><h3 class="h6">Historial</h3><div class="history">${a.history.length?a.history.slice(0,12).map(h=>`<div>${esc(h.msg)} <small>· ${fmtDate(h.t)}</small></div>`).join(''):'Aún no hay acciones.'}</div></div>`}
function renderGrid(){let a=album();$('#numbersTitle').textContent=a.name;let sel=$('#range'),blocks=Math.ceil(a.total/100);sel.innerHTML='<option value="all">Todos los números</option>'+Array.from({length:blocks},(_,i)=>{let st=i*100+1,en=Math.min(a.total,(i+1)*100);return `<option value="${i}">${st}–${en}</option>`}).join('');sel.value=range;let start=1,end=a.total;if(range!=='all'){start=+range*100+1;end=Math.min(a.total,start+99)}let frag=document.createDocumentFragment(),shown=0;for(let n=start;n<=end;n++){let q=a.copies[n]||0,ok=filter==='all'||filter==='missing'&&q===0||filter==='have'&&q>0||filter==='dup'&&q>1;if(!ok)continue;shown++;let b=document.createElement('button');b.className='num '+(q?'have ':'')+(q>1?'dup':'');b.dataset.n=n;b.dataset.qty=q;b.textContent=n;let timer,moved=false;b.addEventListener('pointerdown',()=>{moved=false;timer=setTimeout(()=>{moved=true;openCopies(n)},520)});['pointerup','pointerleave','pointercancel'].forEach(e=>b.addEventListener(e,()=>clearTimeout(timer)));b.onclick=()=>{if(moved)return;action(q?`Quitaste ${n} (ahora falta)`:`Marcaste ${n} (tengo)`,()=>{if(q)delete a.copies[n];else a.copies[n]=1})};frag.append(b)}$('#grid').replaceChildren(frag);$('#summary').textContent=`${shown} números mostrados · ${stats(a).have}/${a.total} conseguidas`}
function tradeText(){let a=album(),miss=[],dup=[];for(let i=1;i<=a.total;i++){let q=a.copies[i]||0;if(!q)miss.push(i);if(q>1)dup.push(`${i} (${q-1})`)}return `Álbum: ${a.name}\nMe faltan: ${miss.length?miss.join(', '):'Ninguna'}\nTengo repetidas: ${dup.length?dup.join(', '):'Ninguna'}`}
function renderTrade(){let a=album(),miss=[],dup=[];for(let i=1;i<=a.total;i++){let q=a.copies[i]||0;if(!q)miss.push(i);if(q>1)dup.push([i,q-1])}$('#missingCount').textContent=`(${miss.length})`;$('#dupCount').textContent=`(${dup.reduce((x,y)=>x+y[1],0)})`;$('#missingList').innerHTML=miss.length?miss.map(n=>`<span>${n}</span>`).join(''):'<span>¡Álbum completo!</span>';$('#dupList').innerHTML=dup.length?dup.map(([n,q])=>`<span>${n} · ${q}×</span>`).join(''):'<span>Sin repetidas</span>'}
function render(){applyTheme();renderCards();renderDash();renderGrid();renderTrade()}
function showView(v){$$('.view').forEach(x=>x.classList.toggle('d-none',x.id!==v));$$('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='numbers')renderGrid();if(v==='trade')renderTrade()}
function openAlbumModal(id=null){editId=id;let a=id?state.albums.find(x=>x.id===id):null;$('#modalTitle').textContent=id?'Editar álbum':'Nuevo álbum';$('#albumName').value=a?.name||'';$('#albumTotal').value=a?.total||100;$('#albumColor').value=a?.color||colors[0];coverData=a?.cover||'';preview();renderPalette();bootstrap.Modal.getOrCreateInstance($('#albumModal')).show()}
function renderPalette(){$('#palette').innerHTML=colors.map(c=>`<button style="background:${c}" data-c="${c}" class="${$('#albumColor').value===c?'active':''}"></button>`).join('');$$('#palette button').forEach(b=>b.onclick=e=>{e.preventDefault();$('#albumColor').value=b.dataset.c;renderPalette()})}
function preview(){$('#coverPreview').style.backgroundImage=coverData?`url('${coverData}')`:''}
function editAlbum(){openAlbumModal(album().id)} window.editAlbum=editAlbum;
function deleteAlbum(){if(state.albums.length===1)return toast('Debe existir al menos un álbum');if(!confirm(`¿Eliminar “${album().name}”?`))return;state.albums=state.albums.filter(a=>a.id!==state.activeId);state.activeId=state.albums[0].id;save();render()} window.deleteAlbum=deleteAlbum;
function clearDups(){let a=album();action('Limpiaste todas las repetidas',()=>Object.keys(a.copies).forEach(k=>{if(a.copies[k]>1)a.copies[k]=1}))}window.clearDups=clearDups;
function resetAlbum(){if(confirm('¿Resetear todas las figuritas de este álbum?'))action('Reiniciaste el álbum',()=>album().copies={})}window.resetAlbum=resetAlbum;window.showView=showView;
function openCopies(n){copyTarget=n;$('#copyNum').textContent=n;$('#copyQty').textContent=album().copies[n]||0;bootstrap.Modal.getOrCreateInstance($('#copiesModal')).show()}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$$('.tabs button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#newAlbum').onclick=$('#newAlbum2').onclick=()=>openAlbumModal();
$('#saveAlbum').onclick=()=>{let name=$('#albumName').value.trim(),total=+$ ('#albumTotal').value,color=$('#albumColor').value;if(!name||total<1||total>5000)return toast('Revisa nombre y total');if(editId){let a=state.albums.find(x=>x.id===editId);a.name=name;a.total=total;a.color=color;a.cover=coverData;a.updatedAt=iso();normalize(a)}else{let a={id:uid(),name,total,color,cover:coverData,copies:{},history:[],updatedAt:iso()};state.albums.push(a);state.activeId=a.id}save();bootstrap.Modal.getInstance($('#albumModal')).hide();render()};
$('#albumColor').oninput=renderPalette;$('#albumCover').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{let im=new Image();im.onload=()=>{let c=document.createElement('canvas'),w=600,h=320;c.width=w;c.height=h;let ctx=c.getContext('2d'),scale=Math.max(w/im.width,h/im.height),sw=w/scale,sh=h/scale;ctx.drawImage(im,(im.width-sw)/2,(im.height-sh)/2,sw,sh,0,0,w,h);coverData=c.toDataURL('image/jpeg',.72);preview()};im.src=r.result};r.readAsDataURL(f)};
$('#filters').onclick=e=>{let b=e.target.closest('button');if(!b)return;filter=b.dataset.filter;$$('#filters button').forEach(x=>x.classList.toggle('active',x===b));renderGrid()};$('#range').onchange=e=>{range=e.target.value;renderGrid()};
$('#jumpBtn').onclick=()=>{let n=+$('#jump').value,a=album();if(n<1||n>a.total)return toast('Número fuera del álbum');range=String(Math.floor((n-1)/100));filter='all';$$('#filters button').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));renderGrid();setTimeout(()=>{let b=$(`#grid [data-n="${n}"]`);b?.scrollIntoView({behavior:'smooth',block:'center'});b?.classList.add('flash')},50)};
$('#copyMinus').onclick=()=>changeCopy(-1);$('#copyPlus').onclick=()=>changeCopy(1);function changeCopy(d){let a=album(),old=a.copies[copyTarget]||0,n=Math.max(0,old+d);action(`Figurita ${copyTarget}: ${n} copia${n===1?'':'s'}`,()=>{if(n)a.copies[copyTarget]=n;else delete a.copies[copyTarget]});$('#copyQty').textContent=n}
$('#undo').onclick=()=>{if(!undoStack.length)return toast('Nada que deshacer');let old=JSON.parse(undoStack.pop()),i=state.albums.findIndex(a=>a.id===old.id);if(i>=0)state.albums[i]=old;save();render();toast('Última acción deshecha')};
$('#copyTrade').onclick=async()=>{await navigator.clipboard.writeText(tradeText());toast('Lista copiada')};$('#waTrade').onclick=()=>window.open('https://wa.me/?text='+encodeURIComponent(tradeText()),'_blank');
$('#export').onclick=()=>{let blob=new Blob([JSON.stringify({app:'Figuritas',version:2,exportedAt:iso(),...state},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`figuritas_2_backup_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u)};$('#import').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(x.v!==2||!Array.isArray(x.albums))throw 0;state={v:2,albums:x.albums,activeId:x.activeId};state.albums.forEach(normalize);if(!album())state.activeId=state.albums[0].id;save();render();toast('Respaldo 2.0 importado')}catch{toast('Archivo no compatible con Figuritas 2.0')}};r.readAsText(f)};
load();render();
